### PR TITLE
Update `ipex-llm` default transformers version to 4.37.0

### PR DESCRIPTION
**Pull request by Oscilloscope98**
## Description

- Update `ipex-llm` default transformers version to 4.37.0
- Update qwen/qwen-vl examples as they requires `transformers<4.37.0`
- Temporarily fix transformers version for some not yet verified examples
- UT update regarding `transformers 4.37.0`

Performance tests: https://github.com/analytics-zoo/nano/issues/1577
Example tests: https://github.com/analytics-zoo/nano/issues/1573

### CODE REVIEW

**Comment by Oscilloscope98** [comment]
PR Validation: https://github.com/intel-analytics/ipex-llm-workflow/actions/runs/10465990770

**Review by liu-shaojun — APPROVED** [review]
LGTM

**Review by rnwang04 — APPROVED** [review]
LGTM

**Comment by Oscilloscope98** [comment]
Updated PR Validation: https://github.com/intel-analytics/ipex-llm-workflow/actions/runs/10468430094

**Pull request merged**
