### PR TITLE
Add Openchat CPU and GPU example

### PR DESCRIPTION
**Pull request by NovTi**
## Description of the changes

This PR adds OpenChat-3.5-0106 model CPU and GPU example using BigDL-LLM transformer and optimize_model API.
Issue page: https://github.com/analytics-zoo/nano/issues/977

### CODE REVIEW

**Comment by Oscilloscope98** [comment]
Please also updated the readme for Windows GPU supports as we have done here: httpshttps://github.com/intel-analytics/BigDL/pull/9992://github.com/intel-analytics/BigDL/pull/9992

It would be better to have some verification on Windows GPU.

**Comment by shane-huang** [comment]
Also need to update the README here https://github.com/intel-analytics/BigDL/blob/main/python/llm/README.md

**Comment by shane-huang** [comment]
please resolve the conflicts.

**Comment by shane-huang** [comment]
and also modify the verified model table in python/llm/README.md

**Pull request closed without merging**
