### PR TITLE
[Orca] Ray Dataset Input Example of PyTorch Estimator

### PR DESCRIPTION
**Pull request by sgwhat**
This example is adapted from
 https://github.com/ray-project/ray/blob/releases/1.9.0/doc/examples/datasets_train/datasets_train.py, 
which mainly handles the data ingest with Ray Datasets and trains a PyTorch deep learning model.

### CODE REVIEW

**Comment by jason-dai** [comment]
1) This example should only support "ray" runtime, no?

2) We may change rename backends of the estimators to "bigdl", "spark" and "ray"? @yushan111 

3) If it runs on "ray" runtime, the estimators should always use "ray" backend, no?

**Comment by sgwhat** [comment]
> 1. This example should only support "ray" runtime, no?
> 2. We may rename backends of the estimators to "bigdl", "spark" and "ray"? @yushan111
> 3. If it runs on "ray" runtime, the estimators should always use "ray" backend, no?

1. Yes, this example only supports "ray" runtime.
3. Yes, we should always use renamed "ray" backend.

**Comment by yushan111** [comment]
> Maybe "bigdl", "spark", "horovod" and "ray"? @yushan111

Sure. I think both backend names of "torch_distrbuted" and "tf2" could be renamed to "ray"

**Comment by yushan111** [comment]
Maybe we don't need users to parse args of "runtime" and "backend", since the example could only run on "ray" runtime and the current "torch_distributed" backend.

**Comment by sgwhat** [comment]
> Maybe we don't need users to parse args of "runtime" and "backend", since the example could only run on "ray" runtime and the current "torch_distributed" backend.

Sure, will be updated soon.

**Pull request closed without merging**
