### PR TITLE
[NPU L0] update layernorm & code refactor

### PR DESCRIPTION
**Pull request by rnwang04**
### 1. Why the change?

https://github.com/analytics-zoo/nano/issues/1622#issuecomment-2441291575

work with https://github.com/intel-analytics/llm.cpp/pull/601

### 2. User API changes

No change.

### 3. Summary of the change 

- Change layernorm from input to const for L0 Llama2
- Code refactor

### 4. How to test?
- [x] Unit test: Please manually trigger the PR Validation [here](https://github.com/intel-analytics/ipex-llm-workflow/actions/workflows/llm-PR-validation.yml) by inputting the PR number (e.g., `1234`). And paste your action link here once it has been successfully finished.
- [x] Application test

### CODE REVIEW

**Review by cyita — APPROVED** [review]
LGTM

**Comment by rnwang04** [comment]
Performance validation is updated here: https://github.com/analytics-zoo/nano/issues/1687#issuecomment-2443318735

**Review by jason-dai — APPROVED** [review]
LGTM

**Review by jason-dai — APPROVED** [review]
LGTM

**Comment by rnwang04** [comment]
PR validation is passed: https://github.com/intel-analytics/ipex-llm-workflow/actions/runs/11568598763/job/32200894388

**Pull request merged**
