### PR TITLE
Fix wrong output For Llama-2-7b-chat-hf on CPU

### PR DESCRIPTION
**Pull request by gc-fu**
## Description

Fix wrong output for Llama-2-7b-chat-hf

Related issues: https://github.com/intel-analytics/ipex-llm/issues/10724

Result on generate.py:

```
-------------------- Prompt --------------------

[INST] <<SYS>>
You are a helpful assistant.
<</SYS>>
What is AI?[/INST]

-------------------- Output --------------------

[INST] <<SYS>>
You are a helpful assistant.
<</SYS>>
What is AI?[/INST]
Ah, a great question! AI, or Artificial Intelligence, refers to the development of computer systems that can perform tasks that typically require human intelligence

```

### CODE REVIEW

**Comment by jenniew** [comment]
For my new findings, let's take a closer look at what's the exact reason.

**Comment by jenniew** [comment]
Please test if output_attentions=True, the result is correct too.

**Review by jenniew — APPROVED** [review]
LGTM

**Comment by gc-fu** [comment]
Tested with `output_attentions=True` and `output_attentions=False`, both are correct

**Pull request merged**
